# Generated by Django 2.2.3 on 2020-04-19 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Users',
        ),
    ]
